/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views.auth;

import javax.swing.JOptionPane;
import views.MenuUtama;

/**
 *
 * @author Elza Kayla
 */
public class Login extends javax.swing.JFrame {

        public Login() {
                initComponents();
        }

        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jpanel = new javax.swing.JPanel();
                loginTitle = new javax.swing.JLabel();
                usernameText = new javax.swing.JLabel();
                passwordText = new javax.swing.JLabel();
                usernameField = new javax.swing.JTextField();
                login = new javax.swing.JButton();
                exit = new javax.swing.JButton();
                passwordField = new javax.swing.JPasswordField();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
                setUndecorated(true);

                jpanel.setBackground(new java.awt.Color(51, 255, 0));

                loginTitle.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
                loginTitle.setForeground(new java.awt.Color(255, 255, 255));
                loginTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                loginTitle.setText("Login");

                usernameText.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
                usernameText.setForeground(new java.awt.Color(255, 255, 255));
                usernameText.setText("Username");

                passwordText.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
                passwordText.setForeground(new java.awt.Color(255, 255, 255));
                passwordText.setText("Password");

                login.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
                login.setText("Masuk");
                login.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
                login.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                loginActionPerformed(evt);
                        }
                });

                exit.setBackground(new java.awt.Color(0, 51, 51));
                exit.setForeground(new java.awt.Color(255, 255, 255));
                exit.setText("X");
                exit.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                exitActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout jpanelLayout = new javax.swing.GroupLayout(jpanel);
                jpanel.setLayout(jpanelLayout);
                jpanelLayout.setHorizontalGroup(
                                jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jpanelLayout.createSequentialGroup()
                                                                .addContainerGap(129, Short.MAX_VALUE)
                                                                .addGroup(jpanelLayout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                                jpanelLayout.createSequentialGroup()
                                                                                                                .addComponent(exit)
                                                                                                                .addContainerGap())
                                                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                                jpanelLayout.createSequentialGroup()
                                                                                                                .addGroup(jpanelLayout
                                                                                                                                .createParallelGroup(
                                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                                .addGroup(jpanelLayout
                                                                                                                                                .createSequentialGroup()
                                                                                                                                                .addGap(1, 1, 1)
                                                                                                                                                .addComponent(usernameField,
                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                                270,
                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                                                                .addGroup(jpanelLayout
                                                                                                                                                .createSequentialGroup()
                                                                                                                                                .addGap(1, 1, 1)
                                                                                                                                                .addComponent(passwordText))
                                                                                                                                .addGroup(jpanelLayout
                                                                                                                                                .createSequentialGroup()
                                                                                                                                                .addGap(1, 1, 1)
                                                                                                                                                .addComponent(usernameText))
                                                                                                                                .addGroup(jpanelLayout
                                                                                                                                                .createSequentialGroup()
                                                                                                                                                .addGap(87, 87, 87)
                                                                                                                                                .addComponent(login,
                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                                100,
                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                                                                .addComponent(passwordField,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                271,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                                                .addGap(188, 188,
                                                                                                                                188))
                                                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                                jpanelLayout.createSequentialGroup()
                                                                                                                .addComponent(loginTitle,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                405,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                .addGap(118, 118,
                                                                                                                                118)))));
                jpanelLayout.setVerticalGroup(
                                jpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jpanelLayout.createSequentialGroup()
                                                                .addGap(12, 12, 12)
                                                                .addComponent(exit)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(loginTitle)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(usernameText)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(usernameField,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(passwordText)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(passwordField,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(login)
                                                                .addContainerGap(68, Short.MAX_VALUE)));

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jpanel, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
                layout.setVerticalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout
                                                                .createSequentialGroup()
                                                                .addGap(0, 0, Short.MAX_VALUE)
                                                                .addComponent(jpanel,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)));

                pack();
                setLocationRelativeTo(null);
        }// </editor-fold>//GEN-END:initComponents

        private void loginActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_bmasukActionPerformed
                String username = usernameField.getText();
                String password = new String(passwordField.getPassword());

                if (username.equals("admin") && password.equals("admin")) {
                        new MenuUtama().setVisible(true);
                        this.dispose();
                } else {
                        JOptionPane.showMessageDialog(this, "Gagal Masuk");
                }
        }// GEN-LAST:event_bmasukActionPerformed

        private void exitActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton3ActionPerformed
                dispose();
        }// GEN-LAST:event_jButton3ActionPerformed

        /**
         * @param args the command line arguments
         */

        public static void main(String args[]) {
                /* Set the Nimbus look and feel */
                // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
                // (optional) ">
                /*
                 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
                 * look and feel.
                 * For details see
                 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
                 */
                try {
                        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager
                                        .getInstalledLookAndFeels()) {
                                if ("Nimbus".equals(info.getName())) {
                                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
                                        break;
                                }
                        }
                } catch (ClassNotFoundException ex) {
                        java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE,
                                        null, ex);
                } catch (InstantiationException ex) {
                        java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE,
                                        null, ex);
                } catch (IllegalAccessException ex) {
                        java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE,
                                        null, ex);
                } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                        java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE,
                                        null, ex);
                }
                // </editor-fold>
                // </editor-fold>

                /* Create and display the form */
                java.awt.EventQueue.invokeLater(new Runnable() {
                        public void run() {
                                new Login().setVisible(true);
                        }
                });

        }

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton exit;
        private javax.swing.JPanel jpanel;
        private javax.swing.JButton login;
        private javax.swing.JLabel loginTitle;
        private javax.swing.JPasswordField passwordField;
        private javax.swing.JLabel passwordText;
        private javax.swing.JTextField usernameField;
        private javax.swing.JLabel usernameText;
        // End of variables declaration//GEN-END:variables
}
